apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: test-app
  namespace: test-app
  labels:
    app: test-app
spec:
  selector:
    matchLabels:
      app: test-app
  replicas: 3
  strategy:
    blueGreen:
      activeService: test-app
      postPromotionAnalysis:
        templates:
          - templateName: test-app-e2e-tests
  template:
    metadata:
      labels:
        app: test-app
    spec:
     containers:
     - image: "ghcr.io/alphagov/govuk/govuk-replatform-test-app:{{ .Values.appVersion }}"
       name: test-app
       resources: {}
       securityContext:
         allowPrivilegeEscalation: false
         capabilities:
           drop:
             - "ALL"
         readOnlyRootFilesystem: true
       volumeMounts:
         - name: test-app-tmp
           mountPath: /tmp
     securityContext:
       seccompProfile:
         type: RuntimeDefault
       fsGroup: 101
       runAsNonRoot: true
       runAsUser: 101
       runAsGroup: 101
     volumes:
     - name: test-app-tmp
       emptyDir: {}
